CREATE TABLE `WHOLESALE_SUPPLIER` (
	`ws_id` INT NOT NULL AUTO_INCREMENT,
	`ws_name` VARCHAR(255) NOT NULL,
	`ws_location` VARCHAR(255) NOT NULL,
	`ws_addr` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ws_id`)
);

CREATE TABLE `WAREHOUSE` (
	`wh_id` INT NOT NULL AUTO_INCREMENT,
	`i_id` INT NOT NULL,
	`wh_name` VARCHAR(255) NOT NULL,
	`wh_location` VARCHAR(255) NOT NULL,
	`wh_addr` VARCHAR(255) NOT NULL,
	`qty` INT NOT NULL,
	`shelf` VARCHAR(255),
	PRIMARY KEY (`wh_id`,`i_id`)
);

CREATE TABLE `WH_S_SUPPLY` (
	`wh_id` INT NOT NULL,
	`s_id` INT NOT NULL,
	`i_id` INT NOT NULL,
	`date_scheduled` DATE,
	`date_completed` DATE,
	`qty` INT NOT NULL,
	`validated` BINARY DEFAULT 0,
	PRIMARY KEY (`wh_id`,`s_id`,`i_id`)
);

CREATE TABLE `ITEM` (
	`i_id` INT NOT NULL AUTO_INCREMENT,
	`manufacturer` VARCHAR(255) NOT NULL,
	`model` VARCHAR(255) NOT NULL,
	`type` VARCHAR(255) NOT NULL,
	`price` INT NOT NULL,
	PRIMARY KEY (`i_id`)
);

CREATE TABLE `TRANSACTION` (
	`i_id` INT NOT NULL,
	`s_id` INT NOT NULL,
	`c_id` INT NOT NULL,
	`_date` DATE NOT NULL,
	`qty` INT NOT NULL,
	PRIMARY KEY (`i_id`,`s_id`,`c_id`)
);

CREATE TABLE `COSTUMER` (
	`c_id` INT NOT NULL AUTO_INCREMENT,
	`c_name` VARCHAR(255) NOT NULL,
	`c_surename` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`c_id`)
);

CREATE TABLE `STORE` (
	`s_id` INT NOT NULL AUTO_INCREMENT,
	`i_id` INT NOT NULL,
	`s_name` VARCHAR(255) NOT NULL,
	`s_location` VARCHAR(255) NOT NULL,
	`s_addr` VARCHAR(255) NOT NULL,
	`qty` INT NOT NULL,
	`shelf` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`s_id`,`i_id`)
);

CREATE TABLE `WH_WS_SUPPLY` (
	`ws_id` INT NOT NULL,
	`wh_id` INT NOT NULL,
	`i_id` INT NOT NULL,
	`date_scheduled` DATE,
	`date_completed` DATE,
	`ws_price` INT NOT NULL,
	`qty` INT NOT NULL,
	`validated` BINARY DEFAULT 0 ,
	PRIMARY KEY (`ws_id`,`wh_id`,`i_id`)
);

ALTER TABLE `WAREHOUSE` ADD CONSTRAINT `WAREHOUSE_fk0` FOREIGN KEY (`i_id`) REFERENCES `ITEM`(`i_id`);

ALTER TABLE `WH_S_SUPPLY` ADD CONSTRAINT `WH_S_SUPPLY_fk0` FOREIGN KEY (`wh_id`) REFERENCES `WAREHOUSE`(`wh_id`);

ALTER TABLE `WH_S_SUPPLY` ADD CONSTRAINT `WH_S_SUPPLY_fk1` FOREIGN KEY (`s_id`) REFERENCES `STORE`(`s_id`);

ALTER TABLE `WH_S_SUPPLY` ADD CONSTRAINT `WH_S_SUPPLY_fk2` FOREIGN KEY (`i_id`) REFERENCES `ITEM`(`i_id`);

ALTER TABLE `TRANSACTION` ADD CONSTRAINT `TRANSACTION_fk0` FOREIGN KEY (`i_id`) REFERENCES `ITEM`(`i_id`);

ALTER TABLE `TRANSACTION` ADD CONSTRAINT `TRANSACTION_fk1` FOREIGN KEY (`s_id`) REFERENCES `STORE`(`s_id`);

ALTER TABLE `TRANSACTION` ADD CONSTRAINT `TRANSACTION_fk2` FOREIGN KEY (`c_id`) REFERENCES `COSTUMER`(`c_id`);

ALTER TABLE `STORE` ADD CONSTRAINT `STORE_fk0` FOREIGN KEY (`i_id`) REFERENCES `ITEM`(`i_id`);

ALTER TABLE `WH_WS_SUPPLY` ADD CONSTRAINT `WH_WS_SUPPLY_fk0` FOREIGN KEY (`ws_id`) REFERENCES `WHOLESALE_SUPPLIER`(`ws_id`);

ALTER TABLE `WH_WS_SUPPLY` ADD CONSTRAINT `WH_WS_SUPPLY_fk1` FOREIGN KEY (`wh_id`) REFERENCES `WAREHOUSE`(`wh_id`);

ALTER TABLE `WH_WS_SUPPLY` ADD CONSTRAINT `WH_WS_SUPPLY_fk2` FOREIGN KEY (`i_id`) REFERENCES `ITEM`(`i_id`);
